const departmentSuggestLeaderEmployee = {
  BUSINESS_DEVELOPMENT: 4,
  HR: 7,
  LASTMILE: 9,
  MIDLEMILE: 10,
  TRUCK_OPERATION: 11,
  COD: 14,
  LEGAL: 16,
  POST_OFFICES_DEPARTMENT: 17,
  INSPECT_OPERATION: 23,
  OFFICE_DEPARTMENT: 27,
  CONSTRUCTION_GROUND: 28,
  XFAST_DEPARTMENT: 29
}

export default departmentSuggestLeaderEmployee
